# Generated by Django 4.2.4 on 2023-10-20 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attacks', models.CharField(max_length=100)),
                ('weak_to', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500, null=True)),
                ('synopsis', models.CharField(max_length=1000, null=True)),
                ('new_features', models.CharField(blank=True, max_length=500, null=True)),
                ('date_released', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('normal_chests', models.IntegerField()),
                ('key_chests', models.IntegerField()),
                ('completion_chests', models.IntegerField()),
                ('enemies_there', models.ManyToManyField(to='CatQuestipedia.enemies')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='CatQuestipedia.game')),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500, null=True)),
                ('effect', models.CharField(max_length=100)),
                ('lvl_one', models.CharField(blank=True, max_length=100, null=True)),
                ('lvl_two', models.CharField(blank=True, max_length=100, null=True)),
                ('lvl_three', models.CharField(blank=True, max_length=100, null=True)),
                ('lvl_four', models.CharField(blank=True, max_length=100, null=True)),
                ('lvl_five', models.CharField(blank=True, max_length=100, null=True)),
                ('lvl_six', models.CharField(blank=True, max_length=100, null=True)),
                ('lvl_seven', models.CharField(blank=True, max_length=100, null=True)),
                ('lvl_eight', models.CharField(blank=True, max_length=100, null=True)),
                ('lvl_nine', models.CharField(blank=True, max_length=100, null=True)),
                ('lvl_ten', models.CharField(blank=True, max_length=100, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='CatQuestipedia.game')),
            ],
        ),
        migrations.CreateModel(
            name='Quests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tasks', models.CharField(blank=True, max_length=500, null=True)),
                ('monster_list', models.CharField(blank=True, max_length=200, null=True)),
                ('character_list', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(max_length=10)),
                ('lvl', models.IntegerField()),
                ('quest_number', models.IntegerField()),
                ('quest_line', models.CharField(max_length=100)),
                ('xpreward', models.IntegerField(blank=True, null=True)),
                ('goldreward', models.IntegerField(blank=True, null=True)),
                ('miscreward', models.CharField(blank=True, max_length=200, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_name', to='CatQuestipedia.game')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_name', to='CatQuestipedia.locations')),
            ],
        ),
        migrations.CreateModel(
            name='MewGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mode_description', models.CharField(blank=True, max_length=200, null=True)),
                ('rewards', models.BooleanField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mewgame', to='CatQuestipedia.game')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500, null=True)),
                ('set', models.CharField(max_length=50, null=True)),
                ('set_type', models.CharField(max_length=10, null=True)),
                ('type', models.CharField(max_length=50)),
                ('defense', models.CharField(max_length=10)),
                ('health', models.CharField(max_length=10)),
                ('physicalattack', models.CharField(max_length=10)),
                ('magic', models.CharField(max_length=10)),
                ('otherbuffs', models.CharField(blank=True, max_length=200, null=True)),
                ('otherdebuffs', models.CharField(blank=True, max_length=200, null=True)),
                ('maxlvl', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='CatQuestipedia.game')),
            ],
        ),
        migrations.AddField(
            model_name='enemies',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='CatQuestipedia.game'),
        ),
        migrations.AddField(
            model_name='enemies',
            name='locations_found',
            field=models.ManyToManyField(to='CatQuestipedia.locations'),
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='CatQuestipedia.game')),
            ],
        ),
    ]
