# Generated by Django 4.2.4 on 2023-10-22 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatQuestipedia', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playthroughs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('test', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playthroughs', to='CatQuestipedia.game')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playthrough_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quests',
            name='user_quests',
            field=models.ManyToManyField(through='CatQuestipedia.UserQuests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spells',
            name='users',
            field=models.ManyToManyField(through='CatQuestipedia.UserSpells', to=settings.AUTH_USER_MODEL),
        ),migrations.RemoveField(
            model_name='spells',
            name='lvl_eight',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='lvl_five',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='lvl_four',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='lvl_nine',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='lvl_one',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='lvl_seven',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='lvl_six',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='lvl_ten',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='lvl_three',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='lvl_two',
        ),
        migrations.AddField(
            model_name='spells',
            name='maxlvl',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserSpells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_level', models.IntegerField()),
                ('playthrough', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spell_playthrough', to='CatQuestipedia.playthroughs')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_name', to='CatQuestipedia.spells')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playthrough', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_playthrough', to='CatQuestipedia.playthroughs')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_name', to='CatQuestipedia.quests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playthroughs', models.ManyToManyField(blank=True, to='CatQuestipedia.playthroughs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='UserEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_level', models.IntegerField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_name', to='CatQuestipedia.equipment')),
                ('playthrough', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_playthrough', to='CatQuestipedia.playthroughs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='users',
            field=models.ManyToManyField(through='CatQuestipedia.UserEquipment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='playthroughs',
            unique_together={('name', 'game', 'user')},
        ),
    ]
