# Generated by Django 4.2.4 on 2023-10-22 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatQuestipedia', '0003_playthroughs_remove_spells_lvl_eight_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='playthroughs',
            name='user_equipment',
            field=models.ManyToManyField(blank=True, to='CatQuestipedia.userequipment'),
        ),
        migrations.AddField(
            model_name='playthroughs',
            name='user_quests',
            field=models.ManyToManyField(blank=True, to='CatQuestipedia.userquests'),
        ),
        migrations.AddField(
            model_name='playthroughs',
            name='user_spells',
            field=models.ManyToManyField(blank=True, to='CatQuestipedia.userspells'),
        ),
    ]
