# Generated by Django 4.2.4 on 2023-10-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatQuestipedia', '0004_remove_spells_lvl_eight_remove_spells_lvl_five_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playthroughs',
            name='test',
        ),
    ]
