# Generated by Django 4.2.4 on 2023-10-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatQuestipedia', '0006_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='tags',
            field=models.ManyToManyField(blank=True, to='CatQuestipedia.tags'),
        ),
        migrations.AddField(
            model_name='enemies',
            name='tags',
            field=models.ManyToManyField(blank=True, to='CatQuestipedia.tags'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='CatQuestipedia.tags'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, to='CatQuestipedia.tags'),
        ),
        migrations.AddField(
            model_name='locations',
            name='tags',
            field=models.ManyToManyField(blank=True, to='CatQuestipedia.tags'),
        ),
        migrations.AddField(
            model_name='mewgame',
            name='tags',
            field=models.ManyToManyField(blank=True, to='CatQuestipedia.tags'),
        ),
        migrations.AddField(
            model_name='quests',
            name='tags',
            field=models.ManyToManyField(blank=True, to='CatQuestipedia.tags'),
        ),
        migrations.AddField(
            model_name='spells',
            name='tags',
            field=models.ManyToManyField(blank=True, to='CatQuestipedia.tags'),
        ),
    ]
