# Generated by Django 4.2.4 on 2023-10-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatQuestipedia', '0008_alter_tags_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quests',
            name='character_list',
        ),
        migrations.RemoveField(
            model_name='quests',
            name='monster_list',
        ),
        migrations.AlterField(
            model_name='quests',
            name='type',
            field=models.CharField(choices=[('main', 'Main Quest'), ('side', 'Side Quest')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='quests',
            name='character_list',
            field=models.ManyToManyField(blank=True, to='CatQuestipedia.characters'),
        ),
        migrations.AddField(
            model_name='quests',
            name='monster_list',
            field=models.ManyToManyField(blank=True, to='CatQuestipedia.enemies'),
        ),
    ]
