# Generated by Django 4.2.4 on 2023-10-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatQuestipedia', '0011_delete_test_enemies_enemy_alter_characters_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='other')),
            ],
        ),
    ]
