# Generated by Django 4.2.4 on 2023-10-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatQuestipedia', '0014_alter_enemies_locations_found_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemies',
            name='locations_found',
        ),
        migrations.AddField(
            model_name='locations',
            name='mew_game_enemy',
            field=models.ManyToManyField(blank=True, related_name='mewgamelocations', to='CatQuestipedia.enemies'),
        ),
        migrations.AddField(
            model_name='quests',
            name='mew_game_monster',
            field=models.ManyToManyField(blank=True, related_name='mewgamequests', to='CatQuestipedia.enemies'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='enemies_there',
            field=models.ManyToManyField(blank=True, related_name='regulargamelocations', to='CatQuestipedia.enemies'),
        ),
        migrations.AlterField(
            model_name='quests',
            name='monster_list',
            field=models.ManyToManyField(blank=True, related_name='regulargamequests', to='CatQuestipedia.enemies'),
        ),
    ]
