# Generated by Django 4.2.4 on 2023-10-29 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatQuestipedia', '0015_remove_enemies_locations_found_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bosses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bosses')),
                ('attacks', models.CharField(max_length=100)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CatQuestipedia.characters')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatQuestipedia.game')),
                ('tags', models.ManyToManyField(blank=True, to='CatQuestipedia.tags')),
            ],
        ),
    ]
