# Generated by Django 4.2.4 on 2023-10-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatQuestipedia', '0016_bosses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mewgame',
            old_name='mode_name',
            new_name='name',
        ),
    ]
