# Generated by Django 4.2.4 on 2023-11-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatQuestipedia', '0019_game_characters_user_edits_game_enemies_user_edits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='equipment'),
        ),
    ]
