# Generated by Django 4.2.4 on 2023-11-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatQuestipedia', '0021_equipment_image_width_alter_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemies',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enemies',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enemies',
            name='enemy',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='enemies', width_field='image_width'),
        ),
    ]
